# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clients_reference.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientsReference(object):
    def setupUi(self, ClientsReference):
        ClientsReference.setObjectName("ClientsReference")
        ClientsReference.resize(637, 484)
        self.clientTable = QtWidgets.QTableWidget(ClientsReference)
        self.clientTable.setGeometry(QtCore.QRect(10, 90, 621, 381))
        self.clientTable.setColumnCount(3)
        self.clientTable.setObjectName("clientTable")
        self.clientTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.clientTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientTable.setHorizontalHeaderItem(2, item)
        self.groupBox = QtWidgets.QGroupBox(ClientsReference)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 621, 71))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.addNewClient = QtWidgets.QToolButton(self.groupBox)
        self.addNewClient.setGeometry(QtCore.QRect(10, 10, 50, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("venv/icons/new-product.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addNewClient.setIcon(icon)
        self.addNewClient.setIconSize(QtCore.QSize(40, 40))
        self.addNewClient.setObjectName("addNewClient")
        self.editClient = QtWidgets.QToolButton(self.groupBox)
        self.editClient.setGeometry(QtCore.QRect(70, 10, 50, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("venv/icons/edit-product.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editClient.setIcon(icon1)
        self.editClient.setIconSize(QtCore.QSize(40, 40))
        self.editClient.setObjectName("editClient")

        self.retranslateUi(ClientsReference)
        QtCore.QMetaObject.connectSlotsByName(ClientsReference)

    def retranslateUi(self, ClientsReference):
        _translate = QtCore.QCoreApplication.translate
        ClientsReference.setWindowTitle(_translate("ClientsReference", "Справочник контрагентов"))
        item = self.clientTable.horizontalHeaderItem(0)
        item.setText(_translate("ClientsReference", "ИНН"))
        item = self.clientTable.horizontalHeaderItem(1)
        item.setText(_translate("ClientsReference", "Наименование"))
        item = self.clientTable.horizontalHeaderItem(2)
        item.setText(_translate("ClientsReference", "Город"))
        self.addNewClient.setText(_translate("ClientsReference", "..."))
        self.editClient.setText(_translate("ClientsReference", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClientsReference = QtWidgets.QWidget()
    ui = Ui_ClientsReference()
    ui.setupUi(ClientsReference)
    ClientsReference.show()
    sys.exit(app.exec_())
