# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 619)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 131, 81))
        self.groupBox.setObjectName("groupBox")
        self.toolButtonNewOrder = QtWidgets.QToolButton(self.groupBox)
        self.toolButtonNewOrder.setGeometry(QtCore.QRect(10, 20, 50, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("venv/icons/new-order.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonNewOrder.setIcon(icon)
        self.toolButtonNewOrder.setIconSize(QtCore.QSize(40, 40))
        self.toolButtonNewOrder.setObjectName("toolButtonNewOrder")
        self.toolButtonAllOrders = QtWidgets.QToolButton(self.groupBox)
        self.toolButtonAllOrders.setGeometry(QtCore.QRect(70, 20, 50, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("venv/icons/edit-order.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonAllOrders.setIcon(icon1)
        self.toolButtonAllOrders.setIconSize(QtCore.QSize(40, 40))
        self.toolButtonAllOrders.setObjectName("toolButtonAllOrders")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.menuAbout = QtWidgets.QAction(MainWindow)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtWidgets.QAction(MainWindow)
        self.menuHelp.setObjectName("menuHelp")
        self.menuNewOrder = QtWidgets.QAction(MainWindow)
        self.menuNewOrder.setObjectName("menuNewOrder")
        self.menuAllOrders = QtWidgets.QAction(MainWindow)
        self.menuAllOrders.setObjectName("menuAllOrders")
        self.menuProducts = QtWidgets.QAction(MainWindow)
        self.menuProducts.setObjectName("menuProducts")
        self.menuClients = QtWidgets.QAction(MainWindow)
        self.menuClients.setObjectName("menuClients")
        self.menuHimiya = QtWidgets.QAction(MainWindow)
        self.menuHimiya.setObjectName("menuHimiya")
        self.menuTara = QtWidgets.QAction(MainWindow)
        self.menuTara.setObjectName("menuTara")
        self.menu.addAction(self.menuNewOrder)
        self.menu.addAction(self.menuAllOrders)
        self.menu_2.addAction(self.menuHelp)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menuAbout)
        self.menu_3.addAction(self.menuProducts)
        self.menu_3.addAction(self.menuClients)
        self.menu_3.addAction(self.menuHimiya)
        self.menu_3.addAction(self.menuTara)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Заказы"))
        self.toolButtonNewOrder.setText(_translate("MainWindow", "..."))
        self.toolButtonAllOrders.setText(_translate("MainWindow", "..."))
        self.menu.setTitle(_translate("MainWindow", "Заказы"))
        self.menu_2.setTitle(_translate("MainWindow", "О программе"))
        self.menu_3.setTitle(_translate("MainWindow", "Справочники"))
        self.menuAbout.setText(_translate("MainWindow", "О программе"))
        self.menuHelp.setText(_translate("MainWindow", "Справка"))
        self.menuNewOrder.setText(_translate("MainWindow", "Создать новый заказ"))
        self.menuAllOrders.setText(_translate("MainWindow", "Все заказы"))
        self.menuProducts.setText(_translate("MainWindow", "Производимая продукция"))
        self.menuClients.setText(_translate("MainWindow", "Контрагенты"))
        self.menuHimiya.setText(_translate("MainWindow", "Химия"))
        self.menuTara.setText(_translate("MainWindow", "Тара"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
