# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_product.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewProduct(object):
    def setupUi(self, NewProduct):
        NewProduct.setObjectName("NewProduct")
        NewProduct.resize(552, 503)
        self.groupBox = QtWidgets.QGroupBox(NewProduct)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 531, 431))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.label.setObjectName("label")
        self.newProductName = QtWidgets.QLineEdit(self.groupBox)
        self.newProductName.setGeometry(QtCore.QRect(130, 40, 391, 31))
        self.newProductName.setObjectName("newProductName")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_2.setObjectName("label_2")
        self.newProductCode = QtWidgets.QLineEdit(self.groupBox)
        self.newProductCode.setGeometry(QtCore.QRect(130, 80, 211, 31))
        self.newProductCode.setObjectName("newProductCode")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 55, 16))
        self.label_3.setObjectName("label_3")
        self.newProductWeight = QtWidgets.QLineEdit(self.groupBox)
        self.newProductWeight.setGeometry(QtCore.QRect(130, 120, 211, 31))
        self.newProductWeight.setObjectName("newProductWeight")
        self.newProductRegExp = QtWidgets.QLineEdit(self.groupBox)
        self.newProductRegExp.setGeometry(QtCore.QRect(130, 160, 391, 31))
        self.newProductRegExp.setObjectName("newProductRegExp")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 111, 16))
        self.label_4.setObjectName("label_4")
        self.newProductAbout = QtWidgets.QPlainTextEdit(self.groupBox)
        self.newProductAbout.setGeometry(QtCore.QRect(130, 260, 391, 161))
        self.newProductAbout.setObjectName("newProductAbout")
        self.newProductType = QtWidgets.QComboBox(self.groupBox)
        self.newProductType.setGeometry(QtCore.QRect(130, 210, 391, 31))
        self.newProductType.setObjectName("newProductType")
        self.newProductType.addItem("")
        self.newProductType.setItemText(0, "")
        self.newProductType.addItem("")
        self.newProductType.addItem("")
        self.newProductType.addItem("")
        self.newProductType.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 260, 111, 51))
        self.label_6.setObjectName("label_6")
        self.createNewProduct = QtWidgets.QPushButton(NewProduct)
        self.createNewProduct.setGeometry(QtCore.QRect(230, 460, 93, 28))
        self.createNewProduct.setObjectName("createNewProduct")

        self.retranslateUi(NewProduct)
        QtCore.QMetaObject.connectSlotsByName(NewProduct)

    def retranslateUi(self, NewProduct):
        _translate = QtCore.QCoreApplication.translate
        NewProduct.setWindowTitle(_translate("NewProduct", "Создание нового продукта"))
        self.groupBox.setTitle(_translate("NewProduct", "Основные параметры нового продукта"))
        self.label.setText(_translate("NewProduct", "Уникальный код"))
        self.label_2.setText(_translate("NewProduct", "Наименование"))
        self.label_3.setText(_translate("NewProduct", "Вес"))
        self.label_4.setText(_translate("NewProduct", "RegExp"))
        self.newProductType.setItemText(1, _translate("NewProduct", "Клей"))
        self.newProductType.setItemText(2, _translate("NewProduct", "Состав для механизированного нанесения"))
        self.newProductType.setItemText(3, _translate("NewProduct", "Финишный состав"))
        self.newProductType.setItemText(4, _translate("NewProduct", "Выравнивающий состав"))
        self.label_5.setText(_translate("NewProduct", "Вид"))
        self.label_6.setText(_translate("NewProduct", "Описание\n"
"назначение\n"
"продукта"))
        self.createNewProduct.setText(_translate("NewProduct", "Создать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewProduct = QtWidgets.QWidget()
    ui = Ui_NewProduct()
    ui.setupUi(NewProduct)
    NewProduct.show()
    sys.exit(app.exec_())
